### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [bodi2b/intro-data-capstone-biodiversity#5]
(Exceeds Expectations)

Well done on this project! Good job on all the calculations as well as data visualizations. In addition, your presentation slides were very concise and efficient in presenting your findings. Great attention to detail on your charts and descriptions!

As a further challenge, continue exploring these datasets and see if you could ask some more research questions about it. Try designing your own tests and continue to play around with different ways of data visualizations. Have fun!

**Comment by bodi2b** [comment]
Thank you cyouh95 so much for taking time to review my project and made all the valuable suggestions! This course is my first online course and I had a great time studying and working on the projects! Also, I love the comment of (Exceeds Expectations), reminded me test of Ordinary Wizarding Level from Harry Potter, as I am a big fan of Harry Potter!

**Comment by cyouh95** [comment]
Congrats on completing the course, and for passing your O.W.L.'s with flying colors! On to N.E.W.T.s next? 😉 ⚡️
